---
title: "Cardic Health Assessment Tool"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(reshape2)
library(dplyr)
library(plotly)
library(DT)
library(glmnet)
library(caret)
```


Self Assessment
=====================================  

Column {data-height = 4000 .tabset}
-----------------------------------------------------------------------

### User info

```{r}

numericInput("age", "Age", step = 1, value = 40)

selectInput("sex", "Sex", choices = list("Male", "Female"), selected = "Male")

numericInput("height", "Height (cm)", step = 1, value = 170)

numericInput("weight", "Weight (kg)", step = 1, value = 70)

selectInput("smoke", "Do you smoke?", choices = list("Yes", "No"), selected = "No")

selectInput("alco", "Do you use alcohol?", choices = list("Yes", "No"), selected = "No")

selectInput("active", "Do you exercise?", choices = list("Yes", "No"), selected = "No")

```


Column
----------------------------------------------------------------------

### User info

```{r}

sliderInput("ap_hi", "Systolic Blood Pressure (mmHg)", min = 80, max = 200, value = 120)

sliderInput("ap_lo", "Diastolic Blood Pressure (mmHg)", min = 40, max = 120, value = 80)

checkboxInput("idkbp", "IDK my blood pressure.", value = FALSE)

sliderInput("chol", "Serum Cholestoral (mg/dL)", min = 120, max = 600, value = 200)

checkboxInput("idkchol", "IDK my serum cholesterol.", value = FALSE)

sliderInput("gluc", "Fasting Blood Sugar (mg/dL)", min = 50, max = 200, value = 80)

checkboxInput("idkgluc", "IDK my blood sugar.", value = FALSE)

actionButton("submit", "Get my cardic health estimate")
```


Column
-----------------------------------------------------------------------

### Result 

```{r}

results = eventReactive(input$submit, {
  
  if(input$sex == "Male") user_sex = 2 else user_sex = 1
  
  if(input$idkbp) {
    if(input$age < 30) age_bp = 30
    else if(input$age > 65) age_bp = 65
    else age_bp = input$age
    user_ap_hi = cardio %>% 
      mutate(age = round(age, digits = 0)) %>%
      filter(age == age_bp) %>%
      filter(sex == user_sex) %>%
      select(ap_hi) %>%
      colMeans()
    user_ap_lo = cardio %>% 
      mutate(age = round(age, digits = 0)) %>%
      filter(age == age_bp) %>%
      filter(sex == user_sex) %>%
      select(ap_lo) %>%
      colMeans()
  } else {
    user_ap_hi = input$ap_hi
    user_ap_lo = input$ap_lo
  }
  
  if(input$idkchol) {
    if(input$age < 30) age_chol = 30
    else if(input$age > 65) age_chol = 65
    else age_chol = input$age
    user_chol = cardio_int %>%
      filter(age == age_chol) %>%
      filter(sex == user_sex) %>%
      select(chol) %>%
      colMeans() %>%
      round(digits = 0)
  } else {
    if(input$chol > 240) user_chol = 3
    else if(input$chol > 200) user_chol = 2
    else user_chol = 1
  }
  
  if(input$idkgluc) {
    if(input$age < 30) age_gluc = 30
    else if(input$age > 65) age_gluc = 65
    else age_gluc = input$age
    user_gluc = cardio_int %>%
      filter(age == age_gluc) %>%
      filter(sex == user_sex) %>%
      select(gluc) %>%
      colMeans() %>%
      round(digits = 0)
  } else {
    if(input$gluc > 125) user_gluc = 3
    else if(input$gluc > 100) user_gluc = 2
    else user_gluc = 1
  }
  
  ht_user = data.frame(age = input$age, sex = as.factor(user_sex), 
                       height = input$height, weight = input$weight,
                       ap_hi = user_ap_hi, ap_lo = user_ap_lo, 
                       chol = as.factor(user_chol), gluc = as.factor(user_gluc),
                       smoke = (input$smoke == "Yes"), alco = (input$alco == "Yes"),
                       active = (input$active == "Yes"), output = 0)
  
  ht_user = rbind(ht_test, ht_user)
  
  x_user = model.matrix(output ~ age + sex + height + weight + ap_hi + ap_lo + chol + gluc + smoke + alco + active, data = ht_user)
  
  last(predict(fit1, newx = x_user, s = lambda, type = "response"))
  
})

renderPrint({
  
  req(results())
  
  print(paste("Your chance of getting cardiovescular disease is:", 
        round(results(), digits = 2)))
  
  if(results() < 0.25) print("Congratulations! You have a very strong heart <3")
  else if (results() < 0.5) print("Try a healthier life style, you can do better!")
  else if (results() < 0.75) print("Meh")
  else print("Your heart is in danger... Go see a doctor! NOW!")
  
  print("*Disclaimer: This app is not intended for medical purposes.*")
  
  })

```


Data Set
=====================================  

Column 
-----------------------------------------------------------------------
### Raw data

```{r}
cardio = read_csv2("https://raw.githubusercontent.com/ebifryy/ds4ph_Capstone/main/cardio.csv") %>% 
  rename(sex = gender, chol = cholesterol, output = cardio) %>% 
  select(-id) %>% 
  mutate(age = age/365, weight = weight/10)

ht = cardio %>%
  mutate(sex = as.factor(sex), chol = as.factor(chol), gluc = as.factor(gluc),
         smoke = as.logical(smoke), alco = as.logical(alco), active = as.logical(active))

datatable(head(cardio, 100))

cardio_int = cardio %>% mutate(age = round(age, digits = 0))

dt = sort(sample(nrow(ht), nrow(ht)*.9))
ht_train = ht[dt,]
ht_test = ht[-dt,]
```

Column {data-width = 400}
-----------------------------------------------------------------------
### Description

Data:
<br> A data set containing 70000 records of patient data. The raw data is downloaded from kaggle.com, which is a database website where data sets are publicly accessible for self investigation. A link can be found here: 
<br> [link](https://www.kaggle.com/sulianova/cardiovascular-disease-dataset)

There are 3 types of input features:
<br> Objective: factual information;
<br> Examination: results of medical examination;
<br> Subjective: information given by the patient.

Variables:
<br> 1. Age | Objective  | age | int (days)
<br> 2. Sex | Objective | sex | 1 = Female, 2 = Male |
<br> 3. Height | Objective | height | int (cm) |
<br> 3. Weight | Objective | weight | float (kg) |
<br> 5. Systolic blood pressure | Examination | ap_hi | int |
<br> 6. Diastolic blood pressure | Examination | ap_lo | int |
<br> 7. Cholesterol | Examination | chol | 1: normal (<= 200 mg/dL), 2: above normal (200-140 mg/dL), 3: well above normal (> 240 mg/dL)|
<br> 8. Glucose | Examination | gluc | 1: normal (<= 100 mg/dL), 2: above normal (100-125 mg/dL), 3: well above normal (> 125 mg/dL) |
<br> 9. Smoking | Subjective | smoke | binary |
<br> 10. Alcohol intake | Subjective | alco | binary |
<br> 11. Physical activity | Subjective | active | binary |
<br> 12. Presence or absence of cardiovascular disease | Target Variable | cardio | binary |

<br> All of the dataset values were collected at the moment of medical examination.


Column {data-width = 400}
-----------------------------------------------------------------------
### Correlation between variables

```{r}
cormat <- round(cor(cardio),2)
melted_cormat <- melt(cormat)
g = ggplot(data = melted_cormat, aes(x = Var1, y = Var2, fill = value)) 
g + geom_tile()
```

### Data distribution by sex

```{r}
tbl <- with(cardio, table(sex, output))

ggplot(as.data.frame(tbl), aes(factor(output), Freq, fill = sex)) +     
  geom_col(position = 'dodge')
```


Logistic Regression Model
=====================================  

Column
-----------------------------------------------------------------------
### GLM

```{r}
fit = glm(formula = output ~ age + sex + height + weight + ap_hi + ap_lo + chol + gluc + smoke + alco + active,
          family = "binomial", data = ht_train)

as.matrix(coef(fit))

prob = exp(predict(fit)) / (1 + exp(predict(fit)))

predict = rep(0, nrow(ht))
predict[prob > .5] = 1

conf_matrix = table(predicted_values = predict, actual_values = ht$output)

accuracy = mean(predict == ht$output)
sens = sensitivity(conf_matrix)
spec = specificity(conf_matrix)

paste("accuracy:", accuracy)
paste("sensitivity:", sens)
paste("specificity:", spec)
```


Column
-----------------------------------------------------------------------
### Lasso GLM

```{r}
x_train = model.matrix(output ~ age + sex + height + weight + ap_hi + ap_lo + chol + gluc + smoke + alco + active, data = ht_train)
y_train = ht_train$output

fit1 = cv.glmnet(x_train, y_train, alpha = 0.2, family = "binomial", type.measure = "mse")

lambda = fit1$lambda.1se
coef(fit1,s = lambda)

x_test = model.matrix(output ~ age + sex + height + weight + ap_hi + ap_lo + chol + gluc + smoke + alco + active, data = ht_test)

prob1 = predict(fit1, newx = x_test, s = lambda, type = "response")

predict1 = rep(0, nrow(ht_test))
predict1[prob1 > .5] = 1

conf_matrix1 = table(predicted_values = predict1, actual_values = ht_test$output)

accuracy1 = mean(predict1 == ht_test$output)
sens1 = sensitivity(conf_matrix1)
spec1 = specificity(conf_matrix1)


paste("accuracy:", accuracy1)
paste("sensitivity:", sens1)
paste("specificity:", spec1)
```


